title: DV Journal
description: Notes and tutorials on design verification
theme: jekyll-theme-minimal
baseurl: "/dv-journal"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-sitemap

# Layout defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: false
      read_time: false
      share: false
      related: false

# Font and style customization
minimal_mistakes_skin: "air"  # try "air", "dark", "neon" for different looks
font: "Fira Code"
include:
  - assets/css/custom.css
